-- Matikan perlindungan RLS sementara untuk semua tabel fondasi MVP
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE menus DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_recipes DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
